### ISSUE TITLE
Build Nav Button Component

### ISSUE THREAD

**Issue by booleanmagus** [Red-Lipped-Batfish-NYOI9/Choreify#21]

**Comment by souzadediogo** [comment]
**To-do's:**
- [ ] Create basic component;
- [ ] Create React Router;
- [ ] Set Nav Bar in the App component;
- [ ] Set main container in the App;
- [ ] Set router to display:
    - [ ]  Kanban Container;
    - [ ] Home Container;
    - [ ] My Groups Container;
